Done:
81 : chi-square test
80 : group by + join (using with)


In [4]:
"""
    Problem 81
    fitness: low, medium, medium-high, high
    https://machinelearningmastery.com/chi-squared-test-for-machine-learning/
"""
never_smoked = [113, 113, 110, 159]
former_smokers = [119, 135, 172, 190]
one_to_nine_daily = [77, 91, 86, 65]
at_least_ten_daily = [181, 152, 124, 73]

"""
    Is there a relation between smoking and fitness level ?
"""
import pandas as pd

df = pd.DataFrame({'never_smoked': never_smoked, 
                  'former_smokers': former_smokers, 
                  'one_to_nine_daily': one_to_nine_daily,
                  'at_least_ten_daily': at_least_ten_daily}).T

In [8]:
df.columns = ['low', 'medium', 'med-high', 'high']

In [9]:
df

low  medium  med-high  high
never_smoked        113     113       110   159
former_smokers      119     135       172   190
one_to_nine_daily    77      91        86    65
at_least_ten_daily  181     152       124    73

In [20]:
from scipy.stats import chi2_contingency
from scipy.stats import chi2
print("H0: the distribution of fitness level is independent of smoker status")
print("\n")
# contingency table
table = df
print(table)
print('\n')
stat, p, dof, expected = chi2_contingency(table)
print('Degrees of freedom = {}'.format(dof))
print("The expected values are:")
print(expected)
print("\n")
print("Interpreting the test statistics:")
# interpret test-statistic
prob = 0.95
critical = chi2.ppf(prob, dof)
print('probability=%.3f, critical=%.3f, stat=%.3f' % (prob, critical, stat))
if abs(stat) >= critical:
    print('Dependent (reject H0)')
else:
    print('Independent (fail to reject H0)')
print('\n')    
print("p-value")    
# interpret p-value
alpha = 1.0 - prob
print('significance=%.3f, p=%.3f' % (alpha, p))
if p <= alpha:
    print('Dependent (reject H0)')
else:
    print('Independent (fail to reject H0)')

H0: the distribution of fitness level is independent of smoker status


                    low  medium  med-high  high
never_smoked        113     113       110   159
former_smokers      119     135       172   190
one_to_nine_daily    77      91        86    65
at_least_ten_daily  181     152       124    73


Degrees of freedom = 9
The expected values are:
[[123.75       124.00255102 124.25510204 122.99234694]
 [154.         154.31428571 154.62857143 153.05714286]
 [ 79.75        79.9127551   80.0755102   79.26173469]
 [132.5        132.77040816 133.04081633 131.68877551]]


Interpreting the test statistics:
probability=0.950, critical=16.919, stat=87.273
Dependent (reject H0)


p-value
significance=0.050, p=0.000
Dependent (reject H0)


In [18]:
num_never_smoked = (113 + 113 + 110 + 159) 
num_low_fitness = (113 + 119 + 77 + 181) 
total = (113 + 113 + 110 + 159 + 119 + 135 + 172 + 190 + 77 + 91 + 86 + 65 + 181 + 152 + 124 + 73)

expected_never_smoke_and_low_fitness = num_never_smoked*num_low_fitness/total
expected_never_smoke_and_low_fitness

123.75

In [7]:
"""
    airbnb: channel attribution
"""

import pandas as pd
df = pd.read_csv("../Data/channel_attribution/airbnb_test.csv")

In [2]:
df.head()

id date_account_created     gender   age signup_method language  \
0  5uwns89zht           2014-07-01     FEMALE  35.0      facebook       en   
1  jtl0dijy2j           2014-07-01  -unknown-   NaN         basic       en   
2  xx0ulgorjt           2014-07-01  -unknown-   NaN         basic       en   
3  6c6puo6ix0           2014-07-01  -unknown-   NaN         basic       en   
4  czqhjk3yfe           2014-07-01  -unknown-   NaN         basic       en   

  affiliate_channel affiliate_provider signup_app first_device_type  \
0            direct             direct      Moweb            iPhone   
1            direct             direct      Moweb            iPhone   
2            direct             direct        Web   Windows Desktop   
3            direct             direct        Web   Windows Desktop   
4            direct             direct        Web       Mac Desktop   

   first_browser  
0  Mobile Safari  
1  Mobile Safari  
2         Chrome  
3             IE  
4         Safari

In [11]:
df.dtypes

id                       object
date_account_created     object
gender                   object
age                     float64
signup_method            object
language                 object
affiliate_channel        object
affiliate_provider       object
signup_app               object
first_device_type        object
first_browser            object
dtype: object

In [29]:
len(df['date_account_created'].unique())

92

In [30]:
df['affiliate_channel'].value_counts()

direct           43844
sem-brand        10394
seo               5699
sem-non-brand     1231
other              586
remarketing        172
content            170
Name: affiliate_channel, dtype: int64

In [26]:
def fraction_of_nans(df):
    for column in df.columns.tolist():
        print("{}: {}".format(column, 1-df[column].count()/len(df)))
        
fraction_of_nans(df)        

id: 0.0
date_account_created: 0.0
gender: 0.0
age: 0.4650219015717598
signup_method: 0.0
language: 0.0
affiliate_channel: 0.0
affiliate_provider: 0.0
signup_app: 0.0
first_device_type: 0.0
first_browser: 0.0


In [31]:
import numpy as np
df['age'] = df['age'].astype(np.float32)

In [33]:
"""
    test if all ids are unique
"""
df['id'].nunique() == len(df)

True